### ISSUE TITLE
tox error

### ISSUE THREAD

**Issue by sysnux** [Qotto/smspdu#2]
Hi,
Trying to run tests on a freshly cloned smspdu on python-3.6, I'm getting this error: 

py36 runtests: PYTHONHASHSEED='807310402'
py36 runtests: commands[0] | pip install -r requirements.txt
Requirement already satisfied: bitstring==3.1.5 in ./.tox/py36/lib/python3.6/site-packages (from -r requirements.txt (line 1)) (3.1.5)
Requirement already satisfied: pytz==2017.3 in ./.tox/py36/lib/python3.6/site-packages (from -r requirements.txt (line 2)) (2017.3)
Requirement already satisfied: six==1.11.0 in ./.tox/py36/lib/python3.6/site-packages (from -r requirements.txt (line 3)) (1.11.0)
py36 runtests: commands[1] | mypy smspdu
smspdu/elements.py:205: error: Argument 1 to "get" of "Mapping" has incompatible type "Optional[str]"; expected "str"
smspdu/elements.py:206: error: Argument 1 to "get" of "Mapping" has incompatible type "Optional[str]"; expected "str"
smspdu/fields.py:195: error: Value of type "Optional[Dict[Any, Any]]" is not indexable
smspdu/fields.py:199: error: Value of type "Optional[Dict[Any, Any]]" is not indexable
smspdu/fields.py:201: error: Value of type "Optional[Dict[Any, Any]]" is not indexable
smspdu/fields.py:208: error: Value of type "Optional[Dict[Any, Any]]" is not indexable
ERROR: InvocationError: 'xxxxxx/smspdu/.tox/py36/bin/mypy smspdu'
_____________________________________ summary _____________________________________
ERROR:   py36: commands failed

**Comment by alexpirine** [comment]
Hi,

Thanks for reporting the issue!
